language: cpp
cache: ccache
os: linux
dist: focal
sudo: true

addons:
  apt:
    packages: &pkg_common
    - cmake3
    - cmake3-data
    - clang-format-6.0
    sources: &src_common
    - llvm-toolchain-trusty-6.0
    - ubuntu-toolchain-r-test

matrix:
  # don't use full compiler path
  # (e.g. /usr/bin/g++-7), it will bypass ccache
  fast_finish: true
  include:
  - env:
    - CXX_=g++-7
    - CC_=gcc-7
    - CPACK=ON
    - COVERAGE=OFF
    - BUILD_TYPE=Release
    - DOXYGEN=ON
    addons:
      apt:
        packages:
        - *pkg_common
        - g++-7
        - doxygen
        - doxygen-doc
        - doxygen-latex
        - doxygen-gui
        - graphviz
        sources:
        - *src_common
  - env:
    - CXX_=g++-7
    - CC_=gcc-7
    - CPACK=OFF
    - COVERAGE=ON
    - BUILD_TYPE=Debug
    addons:
      apt:
        packages:
        - *pkg_common
        - g++-7
        sources:
        - *src_common

install:
  - if [ "${COVERAGE}" = "ON" ]; then pip install --user cpp-coveralls; fi
  - CC=${CC_}
  - CXX=${CXX_}
  - ./scripts/install_antlr.sh
  - ./scripts/install_casadi.sh
  - ./scripts/install_googletest.sh

script:
  - ./scripts/format.sh 0
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWITH_TEST=ON -DWITH_COVERAGE=${COVERAGE}
  - make check -j4

after_success:
  - if [ "${CPACK}" = "ON" ]; then cpack -G ZIP; fi
  - if [ "${COVERAGE}" = "ON" ]; then coveralls -r .. -b . -i src --gcov gcov-7; fi
  - if [ "${DOXYGEN}" = "ON" ]; then cd ../doc && doxygen Doxyfile; fi
