language: cpp
cache: ccache
os: linux
dist: trusty
sudo: true

addons:
  apt:
    packages: &pkg_common
    - cmake3
    - cmake3-data
    - clang-format-6.0
    - libboost-filesystem-dev
    - libboost-program-options-dev
    sources: &src_common
    - llvm-toolchain-trusty-6.0
    - ubuntu-toolchain-r-test

matrix:
  # don't use full compiler path
  # (e.g. /usr/bin/g++-7), it will bypass ccache
  fast_finish: true
  include:
  - env:
    - CXX_=g++-8
    - CC_=gcc-8
    - CPACK=ON
    - COVERAGE=OFF
    - BUILD_TYPE=Release
    addons:
      apt:
        packages:
        - *pkg_common
        - g++-8
        sources:
        - *src_common
  - env:
    - CXX_=g++-7
    - CC_=gcc-7
    - CPACK=OFF
    - COVERAGE=ON
    - BUILD_TYPE=Debug
    addons:
      apt:
        packages:
        - *pkg_common
        - g++-7
        sources:
        - *src_common
  - env:
    - CXX_=clang++-6.0
    - CC_=clang-6.0
    - CPACK=OFF
    - COVERAGE=OFF
    - BUILD_TYPE=Release
    addons:
      apt:
        packages:
        - *pkg_common
        - clang++-6.0
        - clang-6.0
        - libc++-dev
        sources:
        - *src_common

install:
  - if [ "${COVERAGE}" = "ON" ]; then pip install --user cpp-coveralls; fi
  - CC=${CC_}
  - CXX=${CXX_}
  - ./scripts/install_deps.sh

script:
  - ./scripts/format.sh 0
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWITH_TEST=ON -DWITH_COVERAGE=${COVERAGE}
  - make check -j4

after_success:
  - if [ "${CPACK}" = "ON" ]; then cpack -G ZIP; fi
  - if [ "${COVERAGE}" = "ON" ]; then coveralls -r .. -b . -i src --gcov gcov-7; fi

deploy:
  provider: releases
  api_key:
    secure: gazTnMPCtND4LqqFPimDm+o0P6/6V+LO1ao/qw/STi9r+HRe02+8zIlErBJOtOakwIowLM5xkSzPcPRN4RYOowGyh/y/m4qDqHTv/AcnS7XWkeC5wSCItr09dLiuQVdpyvmk44emdhMF9NaxOOGZTcdBC/aMqIT7XXBamcOi56cMWZFD6L5dwjDynAihX4Bir6bnNCzsDr3j8rgeobEKhMpWHMwVcQD/5wrf71JEursTCg6S+pl/XXQ4fvtzWY/GrfcITBpbyBwocciF43lpaLMnMkUqINtM1aU9jAh44/AWGf6v+a+SQEQmTdwOpfwa7ewNtPfYlHWdXSTGZ8TzkndsV1S5E7EHCxlP3pHtp71Hdwkn9vkSr9daSAJQQVmsDwD/sk5NGPohvLofBYc06OJcWKNnGvySyPpoa7fRSJUPIG3oP4YG4ahZs724UTU7nsNc51b3NdyzVIle9Xll35Bo6GbfBhGIcSTzDqcm+Tmuy5BQfY59ReeF+lnp59Av2W48I0M9ZzQ5tMe7PN7nIxheHbAn6FA7A/fivnpkttirHoF6sByyOmAZS34RSr53eYCoeZErsPpYFf2e2cUQw1ktufBsYz22CcQPHsBRQdBd168stshq8M9uyo5MNG0tMsM+0pWUVFRmQ5dUwVOYRwQ0sbtETCfT7KYZLo9ViSE=
  file_glob: true
  skip_cleanup: true
  file: "*.zip"
  on:
    tags: true
    condition: $CPACK = ON

#  vim: set et fenc=utf-8 ff=unix sts=0 sw=2 ts=2 :
