language: cpp
env:
  global:
  - LINUX_DIST=trusty
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
  - RUN_TESTS=true
  - COVERAGE=false
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    addons:
      apt:
        packages:
        - g++-5
        - valgrind
        - lcov
        - libxerces-c-dev
        - libboost-filesystem-dev
        - libboost-program-options-dev
        - libicu-dev
        sources:
        - ubuntu-toolchain-r-test

before_install: 

install:
- sudo ./tools/install_xsd_amd64_deb.sh
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
- echo ${PATH}
- echo ${CXX}
- "${CXX} --version"
- "${CXX} -v"
- sudo pip install codecov
- |
  if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
    CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
    mkdir -p ${DEPS_DIR}/cmake
    travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  fi

script:
- mkdir -p build
- cd build
- cmake .. -DWITH_CASADI=OFF -DWITH_TEST=ON
- make -j4
- ctest
- cpack -G ZIP

after_success:
- echo "done"

deploy:
  provider: releases
  api_key:
    secure: gazTnMPCtND4LqqFPimDm+o0P6/6V+LO1ao/qw/STi9r+HRe02+8zIlErBJOtOakwIowLM5xkSzPcPRN4RYOowGyh/y/m4qDqHTv/AcnS7XWkeC5wSCItr09dLiuQVdpyvmk44emdhMF9NaxOOGZTcdBC/aMqIT7XXBamcOi56cMWZFD6L5dwjDynAihX4Bir6bnNCzsDr3j8rgeobEKhMpWHMwVcQD/5wrf71JEursTCg6S+pl/XXQ4fvtzWY/GrfcITBpbyBwocciF43lpaLMnMkUqINtM1aU9jAh44/AWGf6v+a+SQEQmTdwOpfwa7ewNtPfYlHWdXSTGZ8TzkndsV1S5E7EHCxlP3pHtp71Hdwkn9vkSr9daSAJQQVmsDwD/sk5NGPohvLofBYc06OJcWKNnGvySyPpoa7fRSJUPIG3oP4YG4ahZs724UTU7nsNc51b3NdyzVIle9Xll35Bo6GbfBhGIcSTzDqcm+Tmuy5BQfY59ReeF+lnp59Av2W48I0M9ZzQ5tMe7PN7nIxheHbAn6FA7A/fivnpkttirHoF6sByyOmAZS34RSr53eYCoeZErsPpYFf2e2cUQw1ktufBsYz22CcQPHsBRQdBd168stshq8M9uyo5MNG0tMsM+0pWUVFRmQ5dUwVOYRwQ0sbtETCfT7KYZLo9ViSE=
  file_glob: true
  skip_cleanup: true
  file: "*.zip"
  on:
    tags: true
